# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "okafke"
    reviewers:
      - "okafke"
    commit-message:
      prefix: "fix"
      include: "scope"
    groups:
      qodana-deps:
        patterns:
          - "org.jetbrains.qodana*"
        commit-message:
          prefix: "chore"
          include: "scope"
      changelog-deps:
        patterns:
          - "org.jetbrains.changelog*"
        commit-message:
          prefix: "chore"
          include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "okafke"
    reviewers:
      - "okafke"
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions-deps:
        patterns:
          - "*"
